server:
  compression:
    enabled: true
    mimeTypes: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
    minResponseSize: 200

spring:
  application:
    name: Fullstack

  datasource:
    url: jdbc:mysql://localhost:3306/fullstack?useSSL=false
    username: root
    password: admin
    type: "com.zaxxer.hikari.HikariDataSource"

  jpa:
    show-sql: true
    open-in-view: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false